import { Card, CardType } from '../models/Card';

/**
 * 示例卡牌数据
 * 用于测试和展示
 */
export const sampleCards: Card[] = [
  {
    id: "A101_CookeryOutfitter",
    name: "厨具商",
    deck: "A",
    players: "1+",
    desc: ["计分时，每个烹饪设施可以获得1点额外分数。(烤炉不被视为烹饪设施)"],
    vp: 0,
    extraVp: true,
    bonusVp: "每个烹饪设施+1分",
    prerequisite: "",
    costs: [[]],
    conditionalCost: null,
    costText: "",
    fee: null,
    type: CardType.OCCUPATION,
    category: "PointsCategory",
    numbering: "A101",
    holder: false,
    animalHolder: false,
    field: false,
    actionCard: false,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "A102_Fieldsman",
    name: "田地管理员",
    deck: "A",
    players: "1+",
    desc: ["每当你耕种一块田地时，可以额外获得1个谷物。"],
    vp: 0,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[]],
    conditionalCost: null,
    costText: "",
    fee: null,
    type: CardType.OCCUPATION,
    category: "ResourceCategory",
    numbering: "A102",
    holder: false,
    animalHolder: false,
    field: true,
    actionCard: false,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "B201_ClayOven",
    name: "黏土烤炉",
    deck: "B",
    players: "3+",
    desc: ["每回合可以烤2个谷物为5个食物。"],
    vp: 1,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[{ clay: 3 }]],
    conditionalCost: null,
    costText: "3黏土",
    fee: null,
    type: CardType.MINOR,
    category: "CookingCategory",
    numbering: "B201",
    holder: false,
    animalHolder: false,
    field: false,
    actionCard: false,
    cook: true,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "C301_StoneOven",
    name: "石头烤炉",
    deck: "C",
    players: "4+",
    desc: ["每回合可以烤4个谷物为8个食物。"],
    vp: 2,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[{ stone: 3 }]],
    conditionalCost: null,
    costText: "3石头",
    fee: null,
    type: CardType.MAJOR,
    category: "CookingCategory",
    numbering: "C301",
    holder: false,
    animalHolder: false,
    field: false,
    actionCard: false,
    cook: true,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "A103_Shepherd",
    name: "牧羊人",
    deck: "A",
    players: "1+",
    desc: ["每当你获得羊时，可以额外获得1只羊。"],
    vp: 0,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[]],
    conditionalCost: null,
    costText: "",
    fee: null,
    type: CardType.OCCUPATION,
    category: "AnimalCategory",
    numbering: "A103",
    holder: false,
    animalHolder: true,
    field: false,
    actionCard: false,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "B202_BasketWeaver",
    name: "篮子编织者",
    deck: "B",
    players: "3+",
    desc: ["每当你获得芦苇时，可以额外获得1个芦苇。"],
    vp: 1,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[]],
    conditionalCost: null,
    costText: "",
    fee: null,
    type: CardType.MINOR,
    category: "ResourceCategory",
    numbering: "B202",
    holder: false,
    animalHolder: false,
    field: false,
    actionCard: false,
    stats: [],
    infobox: null,
    marked: false
  },
  {
    id: "C302_Fireplace",
    name: "壁炉",
    deck: "C",
    players: "4+",
    desc: ["可以将1只羊烹饪为2个食物，或将1头牛烹饪为3个食物。"],
    vp: 1,
    extraVp: false,
    bonusVp: "",
    prerequisite: "",
    costs: [[{ clay: 2 }]],
    conditionalCost: null,
    costText: "2黏土",
    fee: null,
    type: CardType.MAJOR,
    category: "CookingCategory",
    numbering: "C302",
    holder: false,
    animalHolder: false,
    field: false,
    actionCard: false,
    cook: true,
    stats: [],
    infobox: null,
    marked: false
  }
]; 